### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by vidyak2uiuc** [ADAPT-uiuc/dias#11]
I installed dias using `pip install dias`
However, I get this below error while trying to import "import dias.rewriter"

>>> import dias.rewriter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/shared/vidyak2/cs/lib/python3.10/site-packages/dias/rewriter.py", line 1487, in <module>
    ip.input_transformers_cleanup.append(call_rewrite)
AttributeError: 'NoneType' object has no attribute 'input_transformers_cleanup'

**Comment by baziotis** [comment]
Interesting, did you with IPython?
